package com.nospam.nospam.core.ml

import java.io.File
import kotlinx.coroutines.test.runTest
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Test

/**
 * End-to-end parity with the Python baseline. `hazm_fixture.json` is generated by
 * `export_android_assets.py` from the training venv: for 470 curated + fuzzed
 * inputs it records (a) what real hazm 0.12 normalization produces and (b) the
 * real pipeline's `decision_function` score. If either the hazm port or the
 * tf-idf transform drifts, these tests fail.
 */
class HazmNormalizerTest {

    @Serializable
    private data class HazmFixture(
        val inputs: List<String>,
        val outputs: List<String>,
        val scores: List<Double>,
    )

    private val json = Json { ignoreUnknownKeys = true }

    private fun normalizer(): HazmNormalizer = HazmNormalizer.fromFiles(File("src/main/assets"))
    private fun fixture(): HazmFixture =
        json.decodeFromString(File("src/test/resources/hazm_fixture.json").readText())

    @Test
    fun `preprocess matches hazm exactly on every fixture input`() {
        val normalizer = normalizer()
        val fixture = fixture()
        assertEquals(fixture.inputs.size, fixture.outputs.size)
        for ((input, expected) in fixture.inputs.zip(fixture.outputs)) {
            assertEquals("hazm normalize parity for input $input", expected, normalizer.preprocess(input))
        }
    }

    @Test
    fun `decision matches baseline on every fixture input`() = runTest {
        val normalizer = normalizer()
        val clf = TfidfSpamClassifier.fromJson(
            File("src/main/assets/spam_model.json").readText(),
            normalizer,
        )
        val fixture = fixture()
        for ((input, expectedScore) in fixture.inputs.zip(fixture.scores)) {
            val verdict = clf.classifyText(input)
            assertEquals("score parity for input $input", expectedScore, verdict.score, 1e-6)
            assertEquals("label parity for input $input", expectedScore > 0.0, verdict.isSpam)
        }
    }
}